version: "3.9"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/core
      - ./static:/app/static
    ports:
    - "8000:8000"
    command: >
      bash -c "python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      python manage.py loaddata fixtures/users.json --app accounts.User &&
      python manage.py loaddata fixtures/categories.json --app menu.Category &&
      python manage.py loaddata fixtures/establishments.json --app establishments.Establishment &&
      python manage.py loaddata fixtures/menus.json --app menu.Menu &&
      python manage.py loaddata fixtures/beverages.json --app menu.Beverage &&
      python manage.py loaddata fixtures/establishment_banners.json --app establishments.EstablishmentBanner &&
      gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - db
