version: "3.9"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/core
      - ./static:/core/static
    ports:
    - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
