# Generated by Django 5.0.4 on 2024-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Establishment Partner'), ('admin', 'Administrator')], default='customer', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('not_say', 'Prefer not to say')], default='not_say', max_length=18),
        ),
    ]
