# Generated by Django 5.0.4 on 2024-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='establishments/banners/'),
        ),
    ]
