# Generated by Django 5.0.4 on 2024-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
