# Generated by Django 5.0.4 on 2024-04-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='happy_hour_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='happy_hour_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
