# Generated by Django 5.0.4 on 2024-05-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='street_number',
        ),
    ]
