# Generated by Django 5.0.4 on 2024-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
