# Generated by Django 5.0.4 on 2024-05-07 08:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_establishment_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='establishment',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='banner_image',
        ),
        migrations.CreateModel(
            name='EstablishmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_text', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.ImageField(upload_to='establishments/banners/')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='establishments.establishment')),
            ],
            options={
                'verbose_name': 'Establishment Banner',
                'verbose_name_plural': 'Establishment Banners',
            },
        ),
    ]
