# Generated by Django 5.0.4 on 2024-05-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_alter_establishment_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentbanner',
            name='alternative_text',
        ),
    ]
