# Generated by Django 5.0.4 on 2024-04-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_menu_itemcategory_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='qr_code_image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='happy_hour_end',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='happy_hour_start',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='menu/qr_code_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='menu.menu')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
            },
        ),
    ]
