# Generated by Django 5.0.4 on 2024-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_beverage_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
