# Generated by Django 5.0.4 on 2024-05-06 11:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_beverage_deleted_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
