# Generated by Django 5.0.4 on 2024-06-08 09:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('statistics', django.db.models.manager.Manager()),
            ],
        ),
    ]
