# Generated by Django 5.0.4 on 2024-05-07 08:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
